# Create files with template for new exercise

dir <- "C:/Dropbox/R/FREELANCING/HPI_2021_R_MOOC/kurs/en_exercises/"
name <- "grex2_Basics"
nfiles <- 3
overwrite <- FALSE

# scripts:
fn_s <- paste0(name,"_",1:6,".R")
fc_s <- paste0("codeoceanR::rt_score()\n\n",
					paste0("# A",1:10," ----", collapse="\n\n"),
					'\n\n\n\n# Now continue in "',fn_s[2:6],'"\n\n',
					"# When you are done, submit your score to openHPI with:\n",
					"# codeoceanR::rt_submit()\n\n")
for(i in 1:nfiles) cat(fc_s[i], file=newFilename(paste0(dir, fn_s[i]), overwrite=overwrite, quiet=TRUE)) ; rm(i)

# tests:
fn_t <- paste0(name,"_tests.R")
fn_t2 <- newFilename(paste0(dir, fn_t), overwrite=overwrite, quiet=TRUE)
cat("# ",fn_t,
		"\nlibrary(codeoceanR) # tests.R at https://github.com/openHPI/codeoceanR/tree/main/inst/extdata",
		"\nrt_test_exercise({\n\n", sep="", file=fn_t2)
for(i in 1:nfiles) cat("script",i," <- rt_run_script(\"",fn_s[i],"\") # script ",i," ----\n\n",
								 paste0("rt_test_task(",1:10,", script",i,", xx, xx)", collapse="\n"),
								 "\n\n", sep="", file=fn_t2, append=TRUE)
cat("})\n", file=fn_t2, append=TRUE)



# OLD FUNCTIONS ----------------


#' @title Add task from database to script
#' @description Add a task from the database to `script_x.R`
#'              and the corresponding tests to `tests.R`.
#' @return taskfile
#' @author Berry Boessenkool, \email{berry-b@@gmx.de}, Oct 2020
#' @seealso [rt_setup_exercise]
#'
#' @param tdb       Task database (data.frame with the columns ID, Task, Test)
#' @param id        ID to be selected from `tdb`, e.g. "Q10_2"
#' @param task_nr   Task number to be printed in `script_x.R`, DEFAULT: id
#' @param script_nr Script number to be used for this task. DEFAULT: 1
#' @param dir       Directory. DEFAULT: "exercise99"
#'
rt_add_task <- function(
tdb,
id,
task_nr=id,
script_nr=1,
dir="exercise99"
)
{

if(!id %in% tdb$ID) stop("ID is not in tdb: ", id)

# dir management:
dir <- berryFunctions::normalizePathCP(dir)
if(!dir.exists(dir)) dir.create(dir, recursive=TRUE)

# TASK ----
taskfile <- paste0(dir, "/script_",  script_nr, ".R")
# Write in finished task script:
if(script_nr>1 && !file.exists(taskfile))
	cat(paste0("\n\n# Now continue in script_",script_nr,".R\n"),
			file=paste0(dir,"/script_", script_nr-1,".R"), append=TRUE)
# start new script with instructions:
if(!file.exists(taskfile) || !any(grepl("codeoceanR::rt_score", readLines(taskfile), fixed=TRUE)) )
	cat(if(script_nr==1) "# Submission is due 16:00 CET. In the succeeding 15 minutes you still get 80% of the score.\n\n",
		"# To score, you can save + source the entire script (CTRL + SHIFT + S) to run",
      "\ncodeoceanR::rt_score()\n", file=taskfile, append=TRUE, sep="")

# text of exercise:
te <- tdb[id,'Task']
te <- gsub("\n", "\n# ", te, fixed=TRUE)
te <- gsub("tx_start", paste0("t",task_nr,"_start"), te, fixed=TRUE)
te <- gsub("tx_end"  , paste0("t",task_nr,"_end"  ), te, fixed=TRUE)

# Write task:
cat(paste0("\n\n# Task ",task_nr," -----\n\n# ", te, "\n\n"),
		file=taskfile, append=TRUE)

# TEST ----
testfile <- paste0(dir, "/tests.R")
# Copy template, add generation time:
if(!file.exists(testfile))
  {
  tlines <- readLines(system.file("extdata/template.R", package="codeoceanR"))
  tlines <- sub("Generated by rt_setup_exercise",
  							paste("Generated", Sys.time(), "by rt_setup_exercise"), tlines)
  writeLines(tlines, testfile)
  }

tlines <- readLines(testfile)
# run_script line:
rs <- paste0("script",script_nr," <- rt_run_script(\"script_",script_nr,".R\")")
if(!any(grepl(rs, tlines, fixed=TRUE))) tlines <- sub("# RUN SCRIPT", paste0(rs,"\n# RUN SCRIPT"), tlines)

# test code from database
tt <- tdb[id,"Test"]
if(is.na(tt) || tt=="---")
  {
  toprint <- paste0("task_id <- ",task_nr," # ",task_nr," ------\n\n# ", tt, "\n\n")
  tlines <- sub("# TEST TASK", paste0(toprint,"\n# TEST TASK"), tlines)
  writeLines(tlines, testfile)
  return(taskfile)
  }

# text of test:
tt <- strsplit(tt, "\n")[[1]]
tt <- gsub("\\<scriptx\\>", paste0("script",script_nr), tt)
tt <- gsub("\\<script_x\\>", paste0("script_",script_nr), tt)
tt <- gsub("\\<taskx\\>", task_nr, tt)

# Find pre + post test code:
pp <- substr(tt, 1,3)!="rt_"
l <- length(pp)
b <- min(which(!pp)) # begin actual tests
e <- max(which(!pp)) # end actual tests
pre  <- if(b>1) 1:(b-1) else 0
post <- if(e<l) (e+1):l else 0
mid  <- b:e

toprint <- paste0("task_id <- ",task_nr," # ",task_nr," ------\n",
paste(tt[pre], collapse="\n"),"\nif(\nrt_script_runs(script",script_nr,")\n&&\n",
paste(tt[mid], collapse="\n&&\n"),"\n) npassed <- npassed + 1\n",
paste(tt[post], collapse="\n"), "\n")
tlines <- sub("# TEST TASK", paste0(toprint,"\n# TEST TASK"), tlines, fixed=TRUE)
writeLines(tlines, testfile)
# Output:
return(taskfile)
}




#' @title Format exercise tasks for database
#' @description Take an entire exercise (`script_1.R`, `script_1.R`, `...`, `tests.R`)
#'              and format them to be added to the task database at
#'              <https://docs.google.com/spreadsheets/d/1ggSOYQ_veXgPmvA8cHCLnASkLUvc6-3t6UhJWPRPVoQ>.\cr
#'              Basically, the opposite of [rt_setup_exercise()].
#' @return location of tempfile with data.frame with tasks and reduced tests.
#' @author Berry Boessenkool, \email{berry-b@@gmx.de}, Nov 2020
#' @examples
#' if(FALSE) # suppress automated runs
#' rt_exercise_to_db("C:/Users/berry/Desktop/CORQUIZ")
#'
#' @param dir Directory with `script_1.R`, `script_1.R`, `...`, `tests.R`. DEFAULT: "exercise99"
#' @param ntasks Number of tasks to obtain. DEFAULT: 10
#'
rt_exercise_to_db <- function(
dir="exercise99",
ntasks=10
)
{
dir <- berryFunctions::normalizePathCP(dir)
berryFunctions::checkFile(dir)
fs <- dir(dir, pattern="script_.*.R", full.names=TRUE)
ft <- paste0(dir, "/tests.R")
if(length(fs)<1) stop("No 'script_*.R' files were found at dir: ", dir)
if(!file.exists(ft)) stop("No 'tests.R' file was found at dir: ", dir)
#
select_parts <- function(r, tag="# Task .* -----")
{
lapply(1:ntasks, function(i)
  {
  tbeg <- grep(gsub(".*",i,tag, fixed=TRUE), r, fixed=TRUE)
  if(length(tbeg)==0) return()
  tend <- grep(tag, r)
  tend <- tend[tend>tbeg]
  tend <- if(length(tend)==0)   length(r)   else   min(tend)-1
  out <- gsub("^# ", "", r[tbeg:tend])
  out
  })
}
# scripts
tasks <- sapply(fs, function(f)
	{
	r <- readLines(f)
	r <- r[substr(r,1,25)!="# Now continue in script_"]
	r <- r[r!=""]
  select_parts(r)
  })
tasks <- tasks[!sapply(tasks, is.null)]
tasks <- lapply(tasks, function(x) x[-1])
# tests
r <- readLines(ft)
r <- r[r!="" & r!="&&" & r!="if(" & r!=") npassed <- npassed + 1"]
r <- r[substr(r,1,15)!="rt_script_runs("]
beg <- which(r=="task_id <- 1 # 1 ------")
end <- which(r=="}, silent=TRUE)")
if(length(beg)!=1) stop("The row 'task_id <- 1 # 1 ------' must occur exactly once in tests.R.")
if(length(end)!=1) stop("The row '}, silent=TRUE)' must occur exactly once in tests.R.")
r <- r[beg:(end-1)]
tests <- select_parts(r, "task_id <- .* # .* ------")
tests <- lapply(tests, function(x) x[-1])
tfile <- tempfile(fileext=".xlsx")
openxlsx::write.xlsx(x=data.frame(sapply(tasks, paste, collapse="\n"),
																	sapply(tests, paste, collapse="\n")),
										 file=tfile, colNames=FALSE)
berryFunctions::openFile(tfile)
tfile
}






#' @title Design complete exercise with tasks from database
#' @description Set up an entire exercise (`script_1.R`, `script_1.R`, `...`, `tests.R`).
#'              Uses the google spreadsheet as a database from which tasks can be selected by ID.
#'              To request access to the spreadsheet, go to
#'              <https://docs.google.com/spreadsheets/d/1ggSOYQ_veXgPmvA8cHCLnASkLUvc6-3t6UhJWPRPVoQ>.\cr
#'              The opposite direction is available with [rt_exercise_to_db()].
#' @return taskfile from last call to [rt_add_task]
#' @author Berry Boessenkool, \email{berry-b@@gmx.de}, Oct 2020
#' @examples
#' if(FALSE) # suppress automated runs
#' rt_setup_exercise(dir="C:/Users/berry/Desktop/CORQUIZ",
#' df=read.table(header=TRUE, text="
#' id      task  script
#' Q11_1   1     1
#' Q10_2   2     1
#' Q12_10  3     2
#' Q11_2   4     3
#' Q11_3   5     3"))
#'
#' if(FALSE)
#' unlink("C:/Users/berry/Desktop/CORQUIZ", recursive=TRUE, force=TRUE)
#'
#' if(FALSE)
#' rt_setup_exercise(df=data.frame(id="pack3", task=1, script=1),
#'                   dir="C:/Users/berry/Desktop/CORQUIZ")
#'
#' @param df  Data.frame with id, task, script. See examples.
#' @param dir Directory. May not yet exist to avoid overwriting. DEFAULT: "exercise99"
#' @param email Google email account with access to the spreadsheet.
#'
rt_setup_exercise <- function(
df,
dir="exercise99",
email="berryboessenkool@hotmail.com"
)
{
dir <- berryFunctions::normalizePathCP(dir)
if(dir.exists(dir)) stop("dir already exists. Please choose a new location. path = ", dir)
dir.create(dir, recursive=TRUE)
# write .Rproj file
rprojfile <- paste0(dir, "/zz_R_exercise.Rproj")
rprojfile <- berryFunctions::normalizePathCP(rprojfile)
cat("Version: 1.0\n\nRestoreWorkspace: No\nSaveWorkspace: No\nEncoding: UTF-8", file=rprojfile)
#
# task database (tdb):
googlesheets4::gs4_auth(email)
tdb <- googlesheets4::read_sheet("1ggSOYQ_veXgPmvA8cHCLnASkLUvc6-3t6UhJWPRPVoQ")
tdb <- as.data.frame(tdb)
rownames(tdb) <- tdb$ID
if(identical(df, "all")) df <- data.frame(id=tdb$ID, task=1:nrow(tdb), script=1)
if(requireNamespace("pbapply", quietly=TRUE)) lapply <- pbapply::pblapply
out <- lapply(1:nrow(df), function(i)
	rt_add_task(tdb=tdb, id=df$id[i], task_nr=df$task[i], script_nr=df$script[i], dir=dir))
out <- tail(unlist(out),1)
cat("\n\n\n# submit for grading ----\n\n# codeoceanR::rt_submit() # in the console (!),",
		"confirm you really want to submit\n\n", file=out, append=TRUE)
#
# put scripts to Rstudio opened files list:
rt_add_opened_files(dir(dir,pattern="script_"), dir=dir)
rt_add_opened_files("tests.R", dir=dir)
# try to open Rproject:
message("Opening ", rprojfile, "\nOpen manually if this fails.")
berryFunctions::openFile(rprojfile)
#
return(out)
}
