# CodeOcean R exercises
# Berry Boessenkool, berry-b@gmx.de, Jan 2020 - Aug 2021
# Generated by rt_setup_exercise

# This script is run by `rt_score()` (in Rstudio) or by clicking "Score" (in CodeOcean).
# Running this script may never fail on CodeOcean, hence keep it wrapped in `try()`.
# The object 'task_id' must be defined here for the error messages through `rt_warn`.
# The tests must be connected with "&&", not "&" to avoid generating multiple messages.
# ("&&" stops evaluating on the first FALSE it encounters).
# The tests are set up so the rt_warn messages are increasingly specific.
# See also https://github.com/openHPI/codeoceanR#teachers  and
#          https://github.com/openHPI/codeoceanR/blob/main/inst/extdata/tests.R

library(codeoceanR) # for all functions prefixed with rt_
ntests <- 10 # number of tests
npassed <- 0 # number of passed tests
trytests <- try({


# RUN SCRIPT
# Move these to right before the corresponding tests, see Note in README





# TEST TASK

# submission time ----

task_id <- ""
rt_due_warn("2020-11-30 16:30") # 16:00 CET is 15:00 UTC


}, silent=TRUE)
task_id <- "_post"
if(inherits(trytests, "try-error"))
  rt_warn("The test script failed. Sorry for the 0 points right now. ",
  				"You'll have to revert the last thing(s) you did. ",
  				"Please send Berry the logfile below through email or 'Request comments'.\n", trytests)

# Final output -----------------------------------------------------------------

if(npassed>ntests) npassed <- ntests # for Bonus points
cat(ntests, "examples,", npassed, "passed\n")
