#' @title Count assignments to an object in student code
#' @description Internal function to count how often `name` is the target of
#' an assignment (`<-`, `<<-`, `=`, `->`, `->>`) in `code` (a charstring or
#' vector of lines, as from [rt_run_script]). Uses the actual parse tree
#' ([utils::getParseData]), so comments, strings, function argument defaults
#' (`x=5` in `function(x=5)`) and named call arguments (`mean(x=5)`) do not
#' cause false positives.
#' @return Integer count of assignments to `name`.
#'         `NA` if `code` can not be parsed
#'         (should not happen for a script that ran successfully in [rt_run_script]).
#' @author Berry Boessenkool, \email{berry-b@@gmx.de}, Sep 2026\cr
#'         Function generated by Posit Assistant (Claude Sonnet 5), 2026-09-12
#' @seealso [rt_test_task] (`ndefinitions` argument),
#'          [exercise example](https://github.com/openHPI/codeoceanR/tree/main/inst/extdata) on github
#' @keywords internal
#'
#' @param code Charstring or vector of lines of R code to be parsed,
#'             normally the output of [rt_run_script].
#' @param name Object name (charstring) to count assignments for.
#'
rt_count_assignments <- function(code, name)
{
code <- paste(code, collapse="\n")
parsed <- try(parse(text=code, keep.source=TRUE), silent=TRUE)
if(inherits(parsed, "try-error")) return(NA_integer_)
pd <- utils::getParseData(parsed)
if(nrow(pd)==0) return(0L)
pd$pos <- pd$line1*1e5 + pd$col1 # left-to-right ordering key (ids are not in text order)
at <- pd[pd$token %in% c("LEFT_ASSIGN","EQ_ASSIGN","RIGHT_ASSIGN"), ]
if(nrow(at)==0) return(0L)

# depth-first: name of the first bare SYMBOL reachable from a given node
get_name <- function(id)
	repeat{
	row <- pd[pd$id==id, ]
	if(row$token=="SYMBOL") return(row$text)
	kids <- pd[pd$parent==id, ]
	if(nrow(kids)==0) return(NA_character_)
	id <- kids$id[which.min(kids$pos)]
	}

# name of the object being assigned to (left of <-/<<-/=, right of ->/->>):
get_lhs <- function(assign_id)
	{
	row  <- pd[pd$id==assign_id, ]
	sibs <- pd[pd$parent==row$parent & pd$id!=assign_id, ]
	if(row$token=="RIGHT_ASSIGN")
		{target <- sibs[sibs$pos>row$pos, ]; tid <- target$id[which.min(target$pos)]} else
		{target <- sibs[sibs$pos<row$pos, ]; tid <- target$id[which.max(target$pos)]}
	if(length(tid)==0) return(NA_character_)
	get_name(tid)
	}

lhs <- vapply(at$id, get_lhs, character(1))
sum(lhs==name, na.rm=TRUE)
}
